### ISSUE TITLE
 Add new functionality - Main-Nav

### ISSUE THREAD

**Issue by sthiepaan** [myosotisrose/ufem-project#8]
Expected _Main-Nav_ Module functionality:
- Click _products_ button should behave like a _dropdown menu_
  - _Dropdown menu_ has a scrollable
  - There are 2 lists of anchors, separated with horizontal line
  - First group contains 16 links
  - Second group contains 13 anchors
  - At the end, there is additional anchor with _"More from Google"_ text
- Clicking outside list should close the _dropdown menu_

**Comment by myosotisrose** [comment]
done
